package games.game.kitpvp;

import java.util.ArrayList;
import java.util.Random;

import org.bukkit.ChatColor;

public class Names {

	public static ArrayList<String> names = new ArrayList<String>();
	public static ArrayList<String> special = new ArrayList<String>();
	
	public static String getName(){
		
		names.add("Sammia Ahmed");
		names.add("Victoria Ault");
		names.add("Robert Bailey");
		names.add("Paul Bennett");
		names.add("Stephen Betteridge");
		names.add("Alan Bushell");
		names.add("Stefan Byrne");
		names.add("Donald Campbell");
		names.add("Alan Carter");
		names.add("Christopher Casey");
		names.add("David Crown");
		names.add("Julie Fawcett");
		names.add("Ria Forgie");
		names.add("Patrick Gage");
		names.add("Graham Garner");
		names.add("Alan Goldfield");
		names.add("Jonathan Hamill");
		names.add("Ken Henderson");
		names.add("Shirley Hill");
		names.add("Stephen Hollyer");
		names.add("Shabir Hussain");
		names.add("John Jones");
		names.add("Sheila Kershaw");
		names.add("Wendy Knott");
		names.add("Andrew Lake");
		names.add("John Lavery");
		names.add("Deborah Lawson");
		names.add("Peter Leonard");
		names.add("Bernard Lord");
		names.add("Kevin Matthews");
		names.add("Richard Matthews");
		names.add("Daniel McCabe");
		names.add("Michael McCoy");
		names.add("James Mee");
		names.add("Pauline Moody");
		names.add("Stephen Moore");
		names.add("Sarah Mullen");
		names.add("Gregory Mutch");
		names.add("Stephen Parrott");
		names.add("Madhu Popat");
		names.add("Adam Purkiss");
		names.add("Diana Racey");
		names.add("John Seddon");
		names.add("David Sibbald");
		names.add("Paul Spicer");
		names.add("Carole Sweeney");
		names.add("Peter Toop");
		names.add("David Waite");
		names.add("David Wick");
		names.add("Curtis Williams");
		names.add("Andrew Abel");
		names.add("Mathew Arnold");
		names.add("Katherine Belton");
		names.add("June Bennett");
		names.add("Paul Bennett");
		names.add("Paul Brand");
		names.add("Roger Browne");
		names.add("Michael Coleman");
		names.add("Dawn Donaldson");
		names.add("James Edwards");
		names.add("Linda Edwards");
		names.add("Pamela Finch");
		names.add("Darryl Gallagher");
		names.add("Paul Graham");
		names.add("Roy Green");
		names.add("Miranda Halsey");
		names.add("David Hewlett");
		names.add("Amanda Holiday");
		names.add("Anthony Holmes");
		names.add("Micha Hussain");
		names.add("Jan Johnson");
		names.add("Colin Jones");
		names.add("Howard Judge");
		names.add("Gul Khan");
		names.add("James Killeen");
		names.add("Gary Kirk");
		names.add("Susan Kruszewski");
		names.add("Cressida Luke");
		names.add("Mian Mahmood");
		names.add("Valerie McCluskey");
		names.add("Peter Merrick");
		names.add("Muriel Nelson");
		names.add("Velma Noel");
		names.add("Bachu Patel");
		names.add("Michael Paul");
		names.add("Timothy Reynolds");
		names.add("Steven Rimmer");
		names.add("James Roberts");
		names.add("Christopher Robinson");
		names.add("Martin Sekula");
		names.add("Venizia Sharma");
		names.add("Robert Skilton");
		names.add("Richard Skinner");
		names.add("Andrew Smith");
		names.add("Andrew Sutcliffe");
		names.add("Tina Taylor");
		names.add("Ricky Walton");
		names.add("Lisa White");
		names.add("Gillian Williams");
		names.add("Carl Yoxall");
		names.add("Uqbah Jalali");
		names.add("Mamoon Firman");
		names.add("Mudrik Mady");
		names.add("Ya'qoob Javid");
		names.add("Aaish Kazi");
		names.add("Abdul Jabbaar Hasen");
		names.add("Sultan Amen");
		names.add("Azhaar Javed");
		names.add("Fawzi Yamin");
		names.add("Mamoon Samaan");
		names.add("Mus'ab Ramadan");
		names.add("Quraish Naqvi");
		names.add("Safwaan Alam");
		names.add("Sharaf Jabour");
		names.add("Mudrik Jabara");
		names.add("Murshid Bangura");
		names.add("Mu'taz Ishak");
		names.add("Umar Majeed");
		names.add("Kanaan Parsa");
		names.add("Abdur Raheem Abbasi");
		names.add("Murshid Ansari");
		names.add("Razeen Bacho");
		names.add("Wajdi Abood");
		names.add("Fuaad Naim");
		names.add("Abdullah Koroma");
		names.add("Nawf Ishak");
		names.add("Waleed Farra");
		names.add("Alawi Assad");
		names.add("Rayyaan Arif");
		names.add("Siddeeqi Ameen");
		names.add("Aslam Awan");
		names.add("Aabid Habib");
		names.add("Aatif Mannan");
		names.add("Arafaat Hassan");
		names.add("Sadoon Kazemi");
		names.add("Sad Fawaz");
		names.add("Abdul Ghafoor Iqbal");
		names.add("Aabid Tabatabai");
		names.add("Nazmi Hoque");
		names.add("Fat'hi Hanif");
		names.add("Hishaam Badie");
		names.add("Abdur Raqeeb Ebrahimi");
		names.add("Ameen Jamil");
		names.add("Bassaam Ansari");
		names.add("Kanaan Harron");
		names.add("Saami Madani");
		names.add("Zain Lodi");
		names.add("Shaqeeq Mohiuddin");
		names.add("Ameer Arif");
		names.add("Hamdaan Jaffer");
		names.add("Turki Zaidi");
		names.add("Zaidaan Mansour");
		names.add("Mawdood Salik");
		names.add("Qaaid Soltani");
		names.add("Maahir Sharaf");
		names.add("Haarith Abdoo");
		names.add("Dhaakir Hariri");
		names.add("Shaafi Badour");
		names.add("Aqeel Huda");
		names.add("Abdul Wadood Agha");
		names.add("Abdul Azeez Habeeb");
		names.add("Hasan Nouri");
		names.add("Badraan Arshad");
		names.add("Jam,aan Rais");
		names.add("Muaaid Kaber");
		names.add("Baasim Arif");
		names.add("Musaddiq Mansouri");
		names.add("Ramzi Sani");
		names.add("Abdul Wahaab Yousef");
		names.add("Saamir Beydoun");
		names.add("Waatiq Sulaiman");
		names.add("Abdul Rauf Wahba");
		names.add("Rafeeq Kamali");
		names.add("Saajid Younes");
		names.add("Faaris Eid");
		names.add("Sharaf Ghazi");
		names.add("Kanaan Baluch");
		names.add("Munjid Obeid");
		names.add("Khaleefa Amir");
		names.add("Qais Ozer");
		names.add("Shaheed Safi");
		names.add("Saleel Samara");
		names.add("Arhab Sadri");
		names.add("Waail Yousuf");
		names.add("Haajid Firman");
		names.add("Rasheeq Sharifi");
		names.add("Asghar Bashara");
		names.add("Jawhar Daoud");
		names.add("Fareed Parsa");
		names.add("Husain Rabbani");
		names.add("Waail Faraj");
		names.add("Haaroon Akel");
		names.add("Abdul Baasid Elamin");
		names.add("Mustaba Jaffer");
		names.add("Husaam Shakoor");
		names.add("Dhaahir Hashmi");
		names.add("Iyaad Abdella");
		names.add("Kabeer Samad");
		names.add("Faheem Salloum");
		names.add("Bassil Badour");
		
		names.add("Drew Baxter");
		names.add("Sebastian Barnard");
		names.add("Louie Darke");
		names.add("Tom Baxter");
		names.add("Dan Keem");
		names.add("John Scarce");
		names.add("Donald Trump");
		names.add("Hillary Clinton");
		names.add("Nigel Farage Moustache");
		names.add("Honey G");
		names.add("Max Poo");
		names.add("Ben Tindal");
		names.add("Mrs Darke");
		names.add("Sadiq Khan");
		names.add("Boris Johnson");
		special.add("Drew Baxter");
		special.add("Sebastian Barnard");
		special.add("Louie Darke");
		special.add("Tom Baxter");
		special.add("Dan Keem");
		special.add("John Scarce");
		special.add("Donald Trump");
		special.add("Hillary Clinton");
		special.add("Nigel Farage Moustache");
		special.add("Honey G");
		special.add("Max Poo");
		special.add("Ben Tindal");
		special.add("Mrs Darke");
		special.add("Sadiq Khan");
		special.add("Boris Johnson");
		
		Random ran = new Random();
		return names.get(ran.nextInt(names.size()));
	}
	
	public static ChatColor getRandomColour(){
		
		Random ran = new Random();
		int i = ran.nextInt(12) + 1;
		
		if (i==1) return ChatColor.AQUA;
		if (i==2) return ChatColor.BLUE;
		if (i==3) return ChatColor.DARK_AQUA;
		if (i==4) return ChatColor.DARK_BLUE;
		if (i==5) return ChatColor.DARK_GRAY;
		if (i==6) return ChatColor.DARK_GREEN;
		if (i==7) return ChatColor.DARK_PURPLE;
		if (i==8) return ChatColor.DARK_RED;
		if (i==9) return ChatColor.GOLD;
		if (i==10) return ChatColor.YELLOW;
		if (i==11) return ChatColor.GREEN;
		if (i==12) return ChatColor.LIGHT_PURPLE;
		if (i==13) return ChatColor.RED;
		
		else return ChatColor.GOLD;
		
	}
}
